# Spring properties
spring:
  application:
    name: account-rest-service  # Identify this application

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
