# Spring properties
spring:
  application:
     name: accounts-service  # Service registers under this name

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 1111   # HTTP (Tomcat) port